spring.application.name=shift-scheduling-system
spring.datasource.url=jdbc:postgresql://localhost:5432/shiftscheduling
spring.datasource.username=sathvikreddy
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
